### PR TITLE
Add Algorithm.{START, END} for use with insert_{before,after}

### PR DESCRIPTION
**Pull request by pjz**
Add some symbols to make list manipulation easier

### CODE REVIEW

**Comment by pjz** [comment]
Fixes #7

**Comment by Changaco** [comment]
LGTM

**Comment by whit537** [comment]
@Changaco May I add you to the "Aspen, Python" team, so you can merge PRs such as this one? Here are the repos that team has perms on:

screen shot 2015-05-09 at 10 33 24 pm

**Comment by Changaco** [comment]
@whit537 Yes, I see no reason to decline.

**Comment by whit537** [comment]
@Changaco Invited.

**Pull request merged**
